import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar de la sección Guías
const sidebars: SidebarsConfig = {
  guiasSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
